name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest

      - name: Run Code Linting
        run: |
          flake8 main.py
          flake8 tests/test_main.py

      - name: Run Security Checks
        run: bandit main.py

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Start kube
        run: minikube start

      - name: Eval kube
        run: eval $(minikube docker-env)

      - name: Check working dir content
        working-directory: ${{ github.workspace }}
        run: ls -la

      - name: Docker build
        run: docker buildx build -t fastapi-app:latest --file ./Dockerfile ./

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/deployment.yaml
